function parsave_illicit_supplychain(savefname,EdgeTable,NodeTable,MOV,...
    FLOW,OUTFLOW,TOTCPTL,DTOBDGT,slsuccess,activeroute,STOCK,slperevent,slval,...
    nactnodes,sltot,t_firstmov)

cd C:\Users\nrmagliocca\'Box Sync'\'Data Drive'\model_results\SupplyChain_full_011718
save(savefname,'EdgeTable','NodeTable','MOV','FLOW','OUTFLOW',...
    'TOTCPTL','DTOBDGT','slsuccess','activeroute','STOCK',...
    'slperevent','slval','nactnodes','sltot','t_firstmov','-v7.3')
cd \\asfs.asnet.ua-net.ua.edu\users$\home\nrmagliocca\'My Documents'\MATLAB\NarcoLogic\NarcoABM


end