function parsave_illicit_supplychain(savefname,EdgeTable,NodeTable,MOV,...
    FLOW,OUTFLOW,TOTCPTL,DTOBDGT,slsuccess,activeroute,STOCK,slperevent,...
    nactnodes,sltot,t_firstmov)

cd X:\model_results\SupplyChain_092717
save(savefname,'EdgeTable','NodeTable','MOV','FLOW','OUTFLOW',...
    'TOTCPTL','DTOBDGT','slsuccess','activeroute','STOCK',...
    'slperevent','nactnodes','sltot','t_firstmov','-v7.3')
cd C:\Users\nmagliocca\Documents\Matlab_code\NarcoLogic


end